version: '3'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  camunda:
    image: registry.gitlab.com/atsoukka/robot-rpa-playground/camunda:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
